name: Build and Deploy
on:
  push:
    branches: [main]

  workflow_dispatch:
  
jobs:
  snowpack-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: ls -la
      - run: npm ci
      - run: npm run build
      - name: Committing changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Snowpack Build
          author_email: actions@github.com

  build:
    needs: snowpack-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pages: write
    concurrency:
      group: 'pages'
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
